
client_config_backend: service
client_config_file: client_secrets.json

service_config:
  client_json_file_path: service_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
